services:
  fcp-sfd-portal-stub:
    ports:
      - '3020:3020'
      - '9329:9229'
    networks:
      - fcp-sfd

  document-upload-stub:
    ports:
      - '3021:3021'
      - '9330:9229'
    networks:
      - fcp-sfd

networks:
  fcp-sfd:
    driver: bridge
    name: fcp-sfd
