services:
  fcp-sfd-portal-stub:
    build:
      context: .
      target: development
    environment:
      NODE_ENV: development
      COGNITO_ENABLED: ${COGNITO_ENABLED:-false}
      COGNITO_DOMAIN: ${COGNITO_DOMAIN}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      COGNITO_CLIENT_SECRET: ${COGNITO_CLIENT_SECRET}
      OBJECT_PROCESSOR_HOST: ${OBJECT_PROCESSOR_HOST:-http://document-upload-stub:3021}
      ADDITIONAL_UPLOAD_DOMAINS: ${ADDITIONAL_UPLOAD_DOMAINS:-http://localhost:3021}
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    depends_on:
      - document-upload-stub
    ports:
      - "3020:3020"

  document-upload-stub:
    build:
      context: ./document-upload-stub
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./document-upload-stub/src:/home/node/src
      - ./document-upload-stub/package.json:/home/node/package.json
