services:
  fcp-sfd-portal-stub:
    build:
      context: .
      target: development
    environment:
      NODE_ENV: development
      COGNITO_ENABLED: ${COGNITO_ENABLED:-false}
      COGNITO_DOMAIN: ${COGNITO_DOMAIN}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      COGNITO_CLIENT_SECRET: ${COGNITO_CLIENT_SECRET}
      OBJECT_PROCESSOR_HOST: ${OBJECT_PROCESSOR_HOST:-http://fcp-sfd-object-processor:3004}
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
