name: Publish Hot Fix

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: "094954420758"

jobs:
  build:
    name: CDP-build-hotfix-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0 # Depth 0 is required for branch-based versioning

      - name: Publish Hot Fix
        uses: DEFRA/cdp-build-action/build-hotfix@7fe324bec9987c5a4d0f4724b42e30c282892ceb # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
